name: .NET

on: [push]

env:
  INFORMATIONAL_VERSION: "1.0"
  CONFIGURATION: "Release"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: build
      run: |
        .\build.ps1 build -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION}} -BuildCounter ${{ github.run_number }}
      shell: pwsh
    - name: test
      run: |
        .\build.ps1 test -Configuration ${{ env.CONFIGURATION }}
      shell: pwsh
    - name: build
      run: |
        .\build.ps1 pack -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }}
      shell: pwsh 