name: .NET

on: [push]

env:
  informationalVersion: "1.0"
  version: "${{ github.run_number }}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: build
      run: pwsh ./build.ps1
