name: EdFi.Ods.Api Trigger workflow in Implementation repo

on: push

env:
  INFORMATIONAL_VERSION: "6.0"
  BUILD_INCREMENTER: "1"
  EDFI_ODS_TOKEN: ${{ secrets.EDFI_ODS_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: dispatch to implementation repo
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.EDFI_ODS_TOKEN }}
        repository: bptillman/Ed-Fi-ODS-Implementation
        event-type: on-demand-test
        client-payload: '{"unit":false,"integration":true}'