name: EdFi.Ods.Api Trigger workflow in Implementation repo

on: push

env:
  INFORMATIONAL_VERSION: "6.0"
  BUILD_INCREMENTER: "1"
  EDFI_ODS_TOKEN: ${{ secrets.EDFI_ODS_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: dispatch to implementation repo
      run: curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.EDFI_ODS_TOKEN }}" https://api.github.com/repos/bptillman/Ed-Fi-ODS-Implementation/dispatches -d '{"event_type":"on-demand-test","client_payload":{"integration":true}}'
      shell: pwsh
