name: Manually triggered build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  call-shared-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: ./github/workflows/shared.yml
      with:
        publish: true
