name: Manually triggered build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  call-shared-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkfolder
      run: |
        ls /home/runner/work/Ed-Fi-ODS/Ed-Fi-ODS/.github/workflows
      shell: pwsh
    - uses: ./.github/workflows/action.yml
      with:
        publish: true
