name: Manually triggered build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  call-shared-workflow:
    uses: ./.github/workflows/action.yml
    with:
      publish: true
